export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "primary-fixed": "#7ffc97",
        "tertiary-container": "#c74668",
        "on-background": "#171d16",
        "outline-variant": "#bdcaba",
        "inverse-primary": "#62df7d",
        "outline": "#6e7b6c",
        "background": "#f4fcf0",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ffb95f",
        "surface-dim": "#d5dcd1",
        "on-tertiary-container": "#fffbff",
        "on-secondary-fixed-variant": "#653e00",
        "surface-variant": "#dde5d9",
        "secondary": "#855300",
        "secondary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#005320",
        "inverse-surface": "#2b322b",
        "surface-container": "#e9f0e5",
        "on-surface-variant": "#3e4a3d",
        "inverse-on-surface": "#ecf3e7",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dde5d9",
        "surface-tint": "#006e2d",
        "on-primary-container": "#f7fff2",
        "tertiary-fixed": "#ffd9de",
        "tertiary-fixed-dim": "#ffb2bf",
        "primary-fixed-dim": "#62df7d",
        "on-tertiary-fixed-variant": "#8a143c",
        "surface-bright": "#f4fcf0",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#2a1700",
        "secondary-container": "#fea619",
        "tertiary": "#a72d51",
        "on-error": "#ffffff",
        "surface-container-high": "#e3eadf",
        "primary": "#006b2c",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#3f0016",
        "surface-container-low": "#eff6ea",
        "primary-container": "#00873a",
        "on-primary-fixed": "#002109",
        "on-surface": "#171d16",
        "surface": "#f4fcf0",
        "on-secondary-container": "#684000",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-xl": "48px",
        "stack-xs": "4px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "stack-md": "16px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Be Vietnam Pro"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Be Vietnam Pro"],
        "display-lg": ["Be Vietnam Pro"],
        "headline-lg": ["Be Vietnam Pro"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
